version: '2'

services:
    # redis
    redis:
        image: redis
        ports:
            - "6379:6379"
    # postgres
    postgres:
        image: postgres:9.6.1
        command: "postgres -c log_connections=true -c log_min_duration_statement=0"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=dock
            - POSTGRES_PASSWORD=dock
            - POSTGRES_DB=dock
