version: '2'

services:
    # redis
    redisdb:
        image: redis
        ports:
            - "6379:6379"
        networks:
            default_net:
                ipv4_address: 179.16.238.10
    # postgres
    postgresdb:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=dock
            - POSTGRES_PASSWORD=dock
            - POSTGRES_DB=dock
        networks:
            default_net:
                ipv4_address: 179.16.238.11


# bridge network
networks:
  default_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 179.16.238.0/24
        gateway: 179.16.238.1
